FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o jejak-worker ./cmd/worker

FROM alpine:3.22

ARG BUILD_HASH
ENV APP_BUILD=${BUILD_HASH}

RUN apk add --no-cache ca-certificates && \
    adduser -D -g '' jejak

WORKDIR /app

COPY --from=builder /app/jejak-worker .

USER jejak

CMD ["./jejak-worker"]
