// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"jejak/app"
	"jejak/config"
	"jejak/container"
)

// Injectors from wire.go:

// InitializeWorker builds WorkerContainer
func InitializeWorker() (*container.WorkerContainer, error) {
	appConfig, err := config.LoadAppConfig()
	if err != nil {
		return nil, err
	}
	redisConfig, err := config.LoadRedisConfig()
	if err != nil {
		return nil, err
	}
	workerContainer, err := app.NewAsynqWorker(appConfig, redisConfig)
	if err != nil {
		return nil, err
	}
	return workerContainer, nil
}
