// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"jejak/app"
	"jejak/config"
	"jejak/container"
	"jejak/internal/handlers"
	"jejak/internal/middlewares"
	"jejak/internal/providers"
	"jejak/internal/repositories"
	"jejak/internal/services"
)

// Injectors from wire.go:

// Initialize App
func InitializeApp() (*container.AppContainer, error) {
	appConfig, err := config.LoadAppConfig()
	if err != nil {
		return nil, err
	}
	authConfig, err := config.LoadAuthConfig()
	if err != nil {
		return nil, err
	}
	jwtService := providers.NewJWTProvider(authConfig)
	jwtMiddleware := middlewares.NewJWTMiddleware(jwtService)
	databaseConfig, err := config.LoadDatabaseConfig()
	if err != nil {
		return nil, err
	}
	db, err := providers.NewDBConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	bpsService := services.NewBPSService()
	authService := services.NewAuthService(userService, jwtService, bpsService)
	validate := providers.NewValidator()
	authHandler := handlers.NewAuthHandler(appConfig, authConfig, authService, validate)
	userHandler := handlers.NewUserHandler(userService, validate)
	surveyRepository := repositories.NewSurveyRepository(db)
	assignmentRepository := repositories.NewAssignmentRepository(db)
	logRepository := repositories.NewLogRepository(db)
	answerRepository := repositories.NewAnswerRepository(db)
	fasihConfig, err := config.LoadFasihConfig()
	if err != nil {
		return nil, err
	}
	fasihService := services.NewFasihService(fasihConfig)
	locationRepository := repositories.NewLocationRepository(db)
	areaRepository := repositories.NewAreaRepository(db)
	assignmentService := services.NewAssignmentService(assignmentRepository, logRepository, answerRepository, locationRepository, surveyRepository, areaRepository)
	surveyService := services.NewSurveyService(surveyRepository, assignmentRepository, logRepository, answerRepository, fasihService, assignmentService)
	redisConfig, err := config.LoadRedisConfig()
	if err != nil {
		return nil, err
	}
	client, err := providers.NewAsyncClient(redisConfig)
	if err != nil {
		return nil, err
	}
	surveyHandler := handlers.NewSurveyHandler(surveyService, validate, client)
	assignmentHandler := handlers.NewAssignmentHandler(assignmentService, validate)
	systemHandler := handlers.NewSystemHandler(fasihService, surveyRepository)
	areaService := services.NewAreaService(areaRepository)
	areaHandler := handlers.NewAreaHandler(areaService, validate, appConfig)
	appContainer, err := app.NewFiberApp(appConfig, jwtMiddleware, authHandler, userHandler, surveyHandler, assignmentHandler, systemHandler, areaHandler)
	if err != nil {
		return nil, err
	}
	return appContainer, nil
}
